### ISSUE TITLE
What does the argument for Diminuendo/Crescendo represents?

### ISSUE THREAD

**Issue by AgustinCB** [Euterpea/Euterpea2#24]
Is it the final note velocity?

Also, would it be possible to create a more expressive alias, a la Dur?

Thanks!

**Comment by donya** [comment]
The argument is a percentage increase/decrease governed by the length of the entire value, not the final velocity. Here you can see the effect with Diminuendo (I've formatted the ghci output a bit to make it more readable). Notice what happens to the volumes at the MEvent level, which is what a Music value is processed into just before heading to MIDI output.

Prelude Euterpea> m = line [c 4 qn :+: e 4 qn :+: g 4 qn :+: c 4 qn]
Prelude Euterpea> mp = phrase [Dyn (Diminuendo 0.5)] m
Prelude Euterpea> perform mp
[
MEvent {eTime = 0 % 1, eInst = AcousticGrandPiano, ePitch = 60, eDur = 1 % 2, eVol = 127, ...},
MEvent {eTime = 1 % 2, eInst = AcousticGrandPiano, ePitch = 64, eDur = 1 % 2, eVol = 111, ...},
MEvent {eTime = 1 % 1, eInst = AcousticGrandPiano, ePitch = 67, eDur = 1 % 2, eVol = 95, ...},
MEvent {eTime = 3 % 2, eInst = AcousticGrandPiano, ePitch = 60, eDur = 1 % 2, eVol = 79, ...}]

The volumes decrease to 79 rather than 64 because it does a simple linear interpolation over the entire duration of the value. So, if you used the argument 0.0 then the last note would still have a velocity >0 even if not by a lot.

When using Crescendo, it is important to first use addVolume to set the volume in some way so it is lower, as the default is 127. So, when working with dynamics, I recommend working with the types Music (Pitch,Volume) or Music (AbsPitch,Volume), as Crescendo, Accent, etc are not detectable from a default volume of 127.

Phrase modifiers are one of the lesser used parts of Euterpea, so they were not given other aliases to avoid namespace pollution. However, it would be easy to make your own functions to wrap them for a particular application. For example, you could redo the above example using such a function:

dim amt = phrase [Dyn (Diminuendo amt)]
mp = dim 0.5 m

While on the subject of creating custom things, I should note that it's also possible to define your own interpretations of these phrase modifiers. The HSoM library provides an easy way to do this via Players. In plain vanilla Euterpea you can also create your own algorithm for converting to MEvents, which can be supplied to the playC function (which takes a PlayParams value that has a bunch of things you can customize).

**Comment by AgustinCB** [comment]
Forgot to thank you :). It worked just as you described.

Nice library, by the way.
