### ISSUE TITLE
cabal install Euterpea fails with GHC 8.4.2

### ISSUE THREAD

**Issue by borgauf** [Euterpea/Euterpea2#27]
I'm on Ubuntu 18.10 and have installed Haskell platform from apt-get install, hence, my ghci version is 8.4.2. After `cabal update` and `cabal install Euterpea` I get this:

. . .
Preprocessing library for Stream-0.4.7.2..
Building library for Stream-0.4.7.2..
<command line>: cannot satisfy -package-id QuickCheck-2.11.3-4bkq8vcRuH33iMSCEtmKx6
    (use -v for more information)
cabal: Leaving directory '/tmp/cabal-tmp-26799/Stream-0.4.7.2'
cabal: Error: some packages failed to install:
Euterpea-2.0.6-9WYRT4FxrFdFt5QybfOEoa depends on Euterpea-2.0.6 which failed
to install.
HCodecs-0.5.1-44uJSicsHEc2P5wPu9H8Nn failed during the building phase. The
exception was:
ExitFailure 1
Stream-0.4.7.2-23P7z552nGi9cxf0PWrXXx failed during the building phase. The
exception was:
ExitFailure 1
arrows-0.4.4.2-629WjkmAFZW5P7315whiTW depends on arrows-0.4.4.2 which failed
to install.

Not sure what to do next. . . .

**Comment by donya** [comment]
Hi there, I will have to see if I can reproduce this, check some versions (I was just doing some installs of Euterpea on Ubuntu a couple weeks ago), and get back to you.

Did you install ALSA (sudo apt-get install libasound2-dev)? My recent experience with Euterpea on Debian and Ubuntu was that it gave a lot of cascading package install failures if ALSA wasn't installed first.

**Comment by borgauf** [comment]
libasound2-dev latest.

**Comment by donya** [comment]
So it looks like my Ubuntu test machine for Euterpea is also running 18.10, but apt-get is gave me ghc 8.2.2 rather than 8.4.2. I'm somewhat puzzled as to how you got 8.4. However, I do believe I've had success reports from people with Ubuntu with higher version numbers installed by other maens, so I'm somewhat doubtful that's the issue.

One thing I have run into periodically on linux is having to manually install certain dependencies that seem to time out or otherwise behave strangely with a regular cabal install over the internet. If trying the regular "cabal install Euterpea" fails after a second try (to eliminate the possibility it was timeouts before), I would recommend using the -v flag to get more detailed information on the point of failure. If it's ambiguous even then, try installing the first failed library in the list this way:

cabal get thelibraryname
cd thelibraryname-itsversion
cabal install

In the various classes I've taught with Euterpea in the past, there have been quite a few student setup situations on linux (mostly Ubuntu) that were resolved that way when dependencies failed for unclear reasons.

On the other hand, if -v gives you a very clear error like being unable to resolve version conflicts, then it's another matter and I'd need to see the full transcript.
