### ISSUE TITLE
can't load framework: CoreMIDI

### ISSUE THREAD

**Issue by shawn-kern** [Euterpea/Euterpea2#48]
on macOS 11.2.2 following import, I get "can't load framework: CoreMIDI (not found)" after any function call, eg.
> Prelude Euterpea> devices
> can't load framework: CoreMIDI (not found)

I tried reinstalls specifying the CoreMIDI framework & framework path with ghc-options.

**Comment by MG-ng** [comment]
I'm getting the same error and would be grateful for any help!

**Comment by MG-ng** [comment]
So, I've tried 

> Restarting the core audio demon with 
`sudo launchctl kickstart -kp system/com.apple.audio.coreaudiod`

> Reinstalling Euterpea and HSoM with 
`cabal install Euterpea --ghc-options="-optl-Wl,-framework,CoreMIDI,-framework,CoreAudio" --force-reinstalls`
then
`cabal install HSoM-1.0.0 —reinstall`
(because I read the book)


**I'm running** 
cabal version 2.4.1.0
ghc version 8.6.3

But I think more importantly:
macOS BigSur version 11.2.3
> It worked with Catalina (but I'm not going back because of the book)

eqMac (newest version)
> I also updated from eqMac2 (but I don't think that this is the reason)


Would be really nice to get some hints other than doing an OS rollback 😅
If you need other/more specs/terminal outputs, don't hesitate to ask!

**Comment by donya** [comment]
This is not something I've ever encountered with Mac and unfortunately I do not have a BigSur machine to test on. One question to ask is whether you have any other MIDI-related applications that still work as intended (a DAW, etc.)? 

I suspect the problem is likely not Euterpea itself, since the "devices" function is really a wrapper to print info from Sound.PortMidi in a particular format. 

See if you can do this is GHCi (don't import Euterpea!):
import Sound.PortMidi
countDevices

It should print a number if you have some MIDI devices. If that succeeds and gives you a number >=1, then try

getDeviceInfo 0

All Euterpea is doing with the device function is a pretty print of that so I'm guessing either countDevices or getDeviceInfo will be the point of failure. The next thing to check would be if there is a more recent PortMidi than gets installed with Euterpea right now and if that more recent one has the issue. This can be done by looking at what packages you have

ghc-pkg list 

then unregistering the old one (this will break Euterpea FYI)

ghc-pkg unregister PortMidi-something (use exactly the version shown by the list command)

Then cabal update and install. 

cabal v1-update
cabal v1-install PortMidi
(or if it's a GitHub new version, download the repo and just do "cabal v1-install" from where the .cabal file is)

then try the GHCi tests I gave above. If it suddenly works then it's just a matter of PortMidi update in Euterpea.

Disclaimer: I'm typing out all the ghc-pkg and cabal stuff from memory not from actually testing it myself so there may be typos. I also don't know right now if there is a newer PortMidi version. If there isn't and PortMidi is the point of failure, there is nothing I can do really except to recommend just exporting MIDI files of your work with writeMidi instead of using the real-time playback features.

**Comment by shawn-kern** [comment]
Following the instructions above, PortMidi gave the same framework not found error. After looking further, it looks like there was a ghc issue with frameworks under BigSur that was resolved in v 8.10.3: 
https://gitlab.haskell.org/ghc/ghc/-/issues/18446
I installed 8.10.4 and got an accurate device count using Sound.PortMidi (no framework error), but Euterpea won't install under 8.10.4.
There's a suggested workaround for the framework error under pre-8.10.3 here:
https://www.reddit.com/r/haskell/comments/k9r2cy/workaround_for_haskell_woes_on_macos_11_big_sur/
I haven't yet tried to resolve the Euterpea install errors under 8.10.4 or this workaround to get frameworks working under 8.6.

**Comment by shawn-kern** [comment]
Here is the install dump from "cabal v1-install Euterpea" under 8.10.4:
Building library for HCodecs-0.5.1..
[1 of 7] Compiling Codec.ByteString.Builder ( src/Codec/ByteString/Builder.hs, dist/build/Codec/ByteString/Builder.o, dist/build/Codec/ByteString/Builder.dyn_o )

src/Codec/ByteString/Builder.hs:79:1: warning: [-Wunused-imports]
    The import of ‘Data.Semigroup’ is redundant
      except perhaps to import instances from ‘Data.Semigroup’
    To import instances alone, use: import Data.Semigroup()
   |
79 | import Data.Semigroup
   | ^^^^^^^^^^^^^^^^^^^^^
[2 of 7] Compiling Codec.ByteString.Parser ( src/Codec/ByteString/Parser.hs, dist/build/Codec/ByteString/Parser.o, dist/build/Codec/ByteString/Parser.dyn_o )

src/Codec/ByteString/Parser.hs:143:5: error:
    ‘fail’ is not a (visible) method of class ‘Monad’
    |
143 |     fail  err  = Parser $ \(S _ _ bytes) ->
    |     ^^^^
cabal: Leaving directory '/var/folders/lv/s0wgzzn55hq1gt01sy2jcmxc0000gn/T/cabal-tmp-7891/HCodecs-0.5.1'
Completed    arrows-0.4.4.2
cabal: Error: some packages failed to install:
Euterpea-2.0.8-ILXRoAxvRRABpVfi9AJUyB depends on Euterpea-2.0.8 which failed
to install.
HCodecs-0.5.1-3yXsyRev1IPHRgLsEwaGfd failed during the building phase. The
exception was:
ExitFailure 1

**Comment by MG-ng** [comment]
> For bifurcate working but devices failing, does bifurcate actually make sound and how are you running it? Compiled?

Yeah, you're right. 
`ghc Bifurcate.lhs` and then `./Bifurcate` works fine (with fluidsynth running) while
`ghci Bifurcate.lhs` and then `main` results in the same error message `can't load framework: CoreMIDI (not found)`

**Comment by shawn-kern** [comment]
I got Euterpea working under 8.10.4 with:
cabal v2-install --allow-newer Euterpea

**Comment by shawn-kern** [comment]
I got Euterpea working under 8.10.4 with:
cabal v2-install --allow-newer Euterpea
