### ISSUE TITLE
www.euterpea.com is down.

### ISSUE THREAD

**Issue by free-variation** [Euterpea/Euterpea2#53]
I believe there may be valuable documentation there, such as how to set up a softsynth. 

Thanks.

**Comment by donya** [comment]
I will look into it. May take a few days to resolve.

**Comment by donya** [comment]
I've had to stop the server for now. Still not sure what happened. Will most likely have to restore from a backup but the tutorials and such should be unaffected once I do that.

**Comment by free-variation** [comment]
Thank you Donya.  If there's any way I can help I'd be glad to do so.

**Comment by donya** [comment]
The site should mainly be waiting on DNS stuff to update at this point. Just be aware that when it comes back up, it will do so at first as just http, not https.

**Comment by donya** [comment]
Seems the DNS stuff still won't play ball. I guess this will be more of a slog than I initially anticipated. If anyone needs specific resources/instructions from the site before I get it back to being functional, email me and make sure "Euterpea website" is somewhere in the subject.

**Comment by donya** [comment]
Have had a couple requests for the API quick references. For anyone who needs them, they will be on Google Drive while I'm sorting out the website issues. 

Note-Level Quick Reference: https://drive.google.com/file/d/1wmXAKnahfTqu-5evTCsswCp0g7ni6MJ2/view?usp=sharing
Signal-Level Quick Reference: https://drive.google.com/file/d/1twRMPqIitVUnfSSFGirw2p7Jpb1TYOSR/view?usp=sharing

**Comment by donya** [comment]
Site appears to be working again. Https is set up now too so going to "euterpea.com" should go to the https://www.euterpea.com and it should load. Since the restore broke some things, I restructured the site slightly to reduce the page count and redundancy that was building up with installation stuff. Instructions are just on main page now and will only be there for now. The old download_and_installation page still "exists" (basically in case it's been linked in places externally to the site) but it shouldn't be linked to from anywhere within euterpea.com anymore and won't be updated since it was turning into a mess. 

Some page links got a bit weird in the restore and ended up set to the IP associated with the domain rather than the domain itself. I corrected all the ones I saw so far,  but have not been able to do an exhaustive check of every single link yet. So, if anyone sees nasty-looking IP URL for anything on the site, just replace it with euterpea.com where the IP was and drop me a note about it by email.

**Comment by free-variation** [comment]
Amazing -- thank you so so much @donya. The site responds perfectly to an SSL request now.

**Comment by donya** [comment]
Reopening this issue temporarily since the certificate for the site is causing problems again. Would have been fixed already if the hard drive that had all the stored credentials to connect to the server hadn't gotten toasted recently. It's just an https vs http issue once again so the site should still be accessible by manually adding the http part of the url as http://www.euterpea.com for browsers that don't try to force usage of https.

**Comment by sutyrin** [comment]
May be closed already?)
